# Generated by Django 3.1.7 on 2021-03-07 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobremesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sobremesa', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('valor', models.FloatField()),
                ('tempo_entrega', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('date_sobremesa', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
