# Generated by Django 3.1.7 on 2021-03-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremesa',
            name='nome_loja',
            field=models.CharField(default='Loja', max_length=200),
        ),
    ]
