# Generated by Django 3.1.7 on 2021-03-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
        ('delivery', '0002_sobremesa_nome_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremesa',
            name='loja',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lojas.loja'),
            preserve_default=False,
        ),
    ]
