# Generated by Django 3.1.7 on 2021-03-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_sobremesa_nome_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremesa',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
