# Generated by Django 3.1.7 on 2021-03-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_sobremesa_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremesa',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
