# Generated by Django 3.1.7 on 2021-03-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_sobremesa_foto_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobremesa',
            old_name='foto_receita',
            new_name='foto_sobremesa',
        ),
    ]
